apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
spec:
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: salaheddine10/express-api:V1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          envFrom:
            # Load the environment variables of our go rest api
            - configMapRef:
                name: express-configmap
